export const patients = [
  {
    id: 1,
    name: "Sarah Mitchell",
    init: "SM",
    age: 34,
    gender: "F",
    mrn: "CP-0421",
    time: "2:00 PM",
    type: "Initial — Psych",
    provider: "Dr. A. Johnson, PMHNP",
    ins: true,
    chief:
      "Persistent sadness, low energy, difficulty concentrating for 3 months following job loss.",
    meds: ["None"],
    allergies: "PCN",
    substance: "Social alcohol, denied illicit",
    trauma: "Work-related stress",
    priorTx: "CBT 2022, no hospitalizations",
    support: "Married, strong family support",
    smi: null,
    phq9: {
      score: 12,
      label: "Moderate",
      si: 1,
      items: [2, 1, 2, 1, 1, 2, 1, 1, 1],
    },
    gad7: {
      score: 10,
      label: "Moderate",
      items: [2, 1, 2, 1, 1, 2, 1],
    },
    hxAttempt: false,
    attemptDetail: null,
    activeSI: false,
    controlled: false,
    controlledDetail: null,
    hardStops: [],
    alerts: [],
  },
  {
    id: 2,
    name: "James Keller",
    init: "JK",
    age: 28,
    gender: "M",
    mrn: "CP-0389",
    time: "3:30 PM",
    type: "Initial — Psych",
    provider: "Dr. M. Chen, PMHNP",
    ins: true,
    chief: "Worsening depression, insomnia, hopelessness after recent breakup.",
    meds: ["None"],
    allergies: "NKDA",
    substance: "Alcohol 4–6 drinks/day",
    trauma: "Childhood abuse, domestic violence",
    priorTx: "Inpatient 2024, IOP 2024",
    support: "Lives alone, estranged from family",
    smi: null,
    phq9: {
      score: 21,
      label: "Severe",
      si: 3,
      items: [3, 3, 3, 3, 2, 3, 2, 1, 3],
    },
    gad7: {
      score: 12,
      label: "Moderate",
      items: [2, 2, 2, 1, 2, 1, 2],
    },
    hxAttempt: true,
    attemptDetail: "Tylenol OD 2024 — inpatient ×5d, Memorial",
    activeSI: true,
    controlled: false,
    controlledDetail: null,
    hardStops: [
      {
        code: "SUICIDE_ATTEMPT_HX",
        title: "History of Suicide Attempt — In-Person Required",
        detail:
          "Prior attempt (Tylenol OD, 2024) + active suicidal ideation on intake. Telehealth is not clinically appropriate.",
        action:
          "Refer for immediate in-person psychiatric evaluation. Notify clinical director.",
      },
    ],
    alerts: [
      "PHQ-9 Item 9 = 3 — Active SI reported",
      "Severe PHQ-9 (21/27)",
      "Daily alcohol use — compounding risk",
      "Limited social support",
    ],
  },
  {
    id: 3,
    name: "Maria Lopez",
    init: "ML",
    age: 45,
    gender: "F",
    mrn: "CP-0412",
    time: "4:00 PM",
    type: "Med Management",
    provider: "Dr. A. Johnson, PMHNP",
    ins: true,
    chief:
      "ADHD symptoms impairing work. Requesting Adderall XR transfer from prior prescriber.",
    meds: ["Adderall XR 20mg (external Rx — transfer requested)"],
    allergies: "Sulfa",
    substance: "Denied",
    trauma: "None reported",
    priorTx: "ADHD neuropsych eval 2021",
    support: "Married, 2 children",
    smi: null,
    phq9: {
      score: 7,
      label: "Mild",
      si: 0,
      items: [1, 1, 1, 1, 0, 1, 1, 1, 0],
    },
    gad7: {
      score: 6,
      label: "Mild",
      items: [1, 1, 1, 1, 0, 1, 1],
    },
    hxAttempt: false,
    attemptDetail: null,
    activeSI: false,
    controlled: true,
    controlledDetail: "Adderall XR 20mg — Schedule II stimulant",
    hardStops: [
      {
        code: "CONTROLLED_STIMULANT",
        title: "Controlled Substance — Schedule II Stimulant",
        detail:
          "Patient requesting Adderall XR (Schedule II). Clinic does not manage stimulants via telehealth.",
        action: "Refer to in-person psychiatry. Pull PDMP. Do not prescribe.",
      },
    ],
    alerts: [
      "Controlled substance request — PDMP check required",
      "Verify prior prescriber documentation",
    ],
  },
  {
    id: 4,
    name: "David Reyes",
    init: "DR",
    age: 52,
    gender: "M",
    mrn: "CP-0398",
    time: "4:30 PM",
    type: "Initial — Psych",
    provider: "Dr. M. Chen, PMHNP",
    ins: false,
    chief: "Anxiety, insomnia. Bipolar I. Requesting Xanax for sleep.",
    meds: ["Lithium 900mg (inconsistent)", "Requesting: Xanax 1mg PRN"],
    allergies: "NKDA",
    substance: "Alcohol 2–3×/wk",
    trauma: "MVA 2019",
    priorTx: "3 psych hospitalizations for mania (2015, 2018, 2022)",
    support: "Divorced, adult children",
    smi: "Bipolar I Disorder",
    phq9: {
      score: 14,
      label: "Moderate",
      si: 1,
      items: [2, 2, 2, 2, 1, 2, 1, 1, 1],
    },
    gad7: {
      score: 16,
      label: "Severe",
      items: [3, 2, 3, 2, 2, 2, 2],
    },
    hxAttempt: false,
    attemptDetail: null,
    activeSI: false,
    controlled: true,
    controlledDetail: "Xanax 1mg PRN — Schedule IV benzodiazepine",
    hardStops: [
      {
        code: "CONTROLLED_BENZO",
        title: "Benzodiazepine Request — Not Permitted via Telehealth",
        detail:
          "Requesting Xanax (Schedule IV). Concurrent alcohol use = high-risk combination. Telehealth prescribing prohibited.",
        action:
          "Refer to in-person psychiatry. Document refusal. Do not prescribe.",
      },
      {
        code: "SMI_BIPOLAR_I",
        title: "Bipolar I — Exceeds Telehealth Scope",
        detail:
          "Bipolar I with 3 hospitalizations for mania and current med non-adherence requires in-person monitoring.",
        action:
          "Refer to in-person psychiatry or Community Mental Health Center (CMHC).",
      },
    ],
    alerts: [
      "Insurance NOT verified — do not bill",
      "Benzo + alcohol = high-risk",
      "Lithium non-adherence — safety concern",
    ],
  },
  {
    id: 5,
    name: "Emma Torres",
    init: "ET",
    age: 29,
    gender: "F",
    mrn: "CP-0445",
    time: "5:00 PM",
    type: "Therapy — Initial",
    provider: "S. Wright, LCSW",
    ins: true,
    chief:
      "Generalized anxiety, work stress, and relationship difficulties. Seeking therapy.",
    meds: ["None"],
    allergies: "NKDA",
    substance: "Social alcohol, denied illicit",
    trauma: "Difficult childhood, parental conflict",
    priorTx: "Brief CBT in college",
    support: "Supportive friends, close sibling",
    smi: null,
    phq9: {
      score: 8,
      label: "Mild",
      si: 1,
      items: [1, 1, 2, 1, 0, 1, 1, 0, 1],
    },
    gad7: {
      score: 14,
      label: "Moderate",
      items: [2, 3, 2, 2, 1, 2, 2],
    },
    hxAttempt: false,
    attemptDetail: null,
    activeSI: false,
    controlled: false,
    controlledDetail: null,
    hardStops: [],
    alerts: [
      "GAD-7 Moderate-Severe (14/21) — monitor closely",
      "PHQ-9 Item 9 = 1 — must probe at session",
    ],
  },
];
